class CountryRegionDict:
    def __init__(self):
        self.country_region_dict = {
            "Afghanistan": "Asia",
            "Albania": "Europe",
            "Algeria": "Africa",
            "Andorra": "Europe",
            "Angola": "Africa",
            "Antigua and Barbuda": "North America",
            "Argentina": "South America",
            "Armenia": "Asia",
            "Aruba": "North America",
            "Australia": "Oceania",
            "Austria": "Europe",
            "Azerbaijan": "Asia",
            "Bahamas, The": "North America",
            "Bahrain": "Middle East",
            "Bangladesh": "Asia",
            "Barbados": "North America",
            "Belarus": "Europe",
            "Belgium": "Europe",
            "Belize": "North America",
            "Benin": "Africa",
            "Bhutan": "Asia",
            "Bolivia": "South America",
            "Bosnia and Herzegovina": "Europe",
            "Botswana": "Africa",
            "Brazil": "South America",
            "Brunei Darussalam": "Asia",
            "Bulgaria": "Europe",
            "Burkina Faso": "Africa",
            "Burundi": "Africa",
            "Cabo Verde": "Africa",
            "Cambodia": "Asia",
            "Cameroon": "Africa",
            "Canada": "North America",
            "Central African Republic": "Africa",
            "Chad": "Africa",
            "Chile": "South America",
            "China, People's Republic of": "Asia",
            "Colombia": "South America",
            "Comoros": "Africa",
            "Congo, Dem. Rep. of the": "Africa",
            "Congo, Republic of": "Africa",
            "Costa Rica": "North America",
            "Croatia": "Europe",
            "Cyprus": "Europe",
            "Czech Republic": "Europe",
            "Côte d'Ivoire": "Africa",
            "Denmark": "Europe",
            "Djibouti": "Africa",
            "Dominica": "North America",
            "Dominican Republic": "North America",
            "Ecuador": "South America",
            "Egypt": "Africa",
            "El Salvador": "North America",
            "Equatorial Guinea": "Africa",
            "Eritrea": "Africa",
            "Estonia": "Europe",
            "Eswatini": "Africa",
            "Ethiopia": "Africa",
            "Fiji": "Oceania",
            "Finland": "Europe",
            "France": "Europe",
            "Gabon": "Africa",
            "Gambia, The": "Africa",
            "Georgia": "Asia",
            "Germany": "Europe",
            "Ghana": "Africa",
            "Greece": "Europe",
            "Grenada": "North America",
            "Guatemala": "North America",
            "Guinea": "Africa",
            "Guinea-Bissau": "Africa",
            "Guyana": "South America",
            "Haiti": "North America",
            "Honduras": "North America",
            "Hong Kong SAR": "Asia",
            "Hungary": "Europe",
            "Iceland": "Europe",
            "India": "Asia",
            "Indonesia": "Asia",
            "Iran": "Middle East",
            "Iraq": "Middle East",
            "Ireland": "Europe",
            "Israel": "Middle East",
            "Italy": "Europe",
            "Jamaica": "North America",
            "Japan": "Asia",
            "Jordan": "Middle East",
            "Kazakhstan": "Asia",
            "Kenya": "Africa",
            "Kiribati": "Oceania",
            "Korea, Republic of": "Asia",
            "Kosovo": "Europe",
            "Kuwait": "Middle East",
            "Kyrgyz Republic": "Asia",
            "Lao P.D.R.": "Asia",
            "Latvia": "Europe",
            "Lebanon": "Middle East",
            "Lesotho": "Africa",
            "Liberia": "Africa",
            "Libya": "Africa",
            "Lithuania": "Europe",
            "Luxembourg": "Europe",
            "Macao SAR": "Asia",
            "Madagascar": "Africa",
            "Malawi": "Africa",
            "Malaysia": "Asia",
            "Maldives": "Asia",
            "Mali": "Africa",
            "Malta": "Europe",
            "Marshall Islands": "Oceania",
            "Mauritania": "Africa",
            "Mauritius": "Africa",
            "Mexico": "North America",
            "Micronesia, Fed. States of": "Oceania",
            "Moldova": "Europe",
            "Mongolia": "Asia",
            "Montenegro": "Europe",
            "Morocco": "Africa",
            "Mozambique": "Africa",
            "Myanmar": "Asia",
            "Namibia": "Africa",
            "Nauru": "Oceania",
            "Nepal": "Asia",
            "Netherlands": "Europe",
            "New Zealand": "Oceania",
            "Nicaragua": "North America",
            "Niger": "Africa",
            "Nigeria": "Africa",
            "North Macedonia": "Europe",
            "Norway": "Europe",
            "Oman": "Middle East",
            "Pakistan": "Asia",
            "Palau": "Oceania",
            "Panama": "North America",
            "Papua New Guinea": "Oceania",
            "Paraguay": "South America",
            "Peru": "South America",
            "Philippines": "Asia",
            "Poland": "Europe",
            "Portugal": "Europe",
            "Puerto Rico": "North America",
            "Qatar": "Middle East",
            "Romania": "Europe",
            "Russian Federation": "Europe",
            "Rwanda": "Africa",
            "Saint Kitts and Nevis": "North America",
            "Saint Lucia": "North America",
            "Saint Vincent and the Grenadines": "North America",
            "Samoa": "Oceania",
            "San Marino": "Europe",
            "Saudi Arabia": "Middle East",
            "Senegal": "Africa",
            "Serbia": "Europe",
            "Seychelles": "Africa",
            "Sierra Leone": "Africa",
            "Singapore": "Asia",
            "Slovak Republic": "Europe",
            "Slovenia": "Europe",
            "Solomon Islands": "Oceania",
            "Somalia": "Africa",
            "South Africa": "Africa",
            "South Sudan, Republic of": "Africa",
            "Spain": "Europe",
            "Sri Lanka": "Asia",
            "Sudan": "Africa",
            "Suriname": "South America",
            "Sweden": "Europe",
            "Switzerland": "Europe",
            "Syria": "Middle East",
            "São Tomé and Príncipe": "Africa",
            "Taiwan Province of China": "Asia",
            "Tajikistan": "Asia",
            "Tanzania": "Africa",
            "Thailand": "Asia",
            "Timor-Leste": "Asia",
            "Togo": "Africa",
            "Tonga": "Oceania",
            "Trinidad and Tobago": "North America",
            "Tunisia": "Africa",
            "Turkmenistan": "Asia",
            "Tuvalu": "Oceania",
            "Türkiye, Republic of": "Europe",
            "Uganda": "Africa",
            "Ukraine": "Europe",
            "United Arab Emirates": "Middle East",
            "United Kingdom": "Europe",
            "United States": "North America",
            "Uruguay": "South America",
            "Uzbekistan": "Asia",
            "Vanuatu": "Oceania",
            "Venezuela": "South America",
            "Vietnam": "Asia",
            "West Bank and Gaza": "Middle East",
            "Yemen": "Middle East",
            "Zambia": "Africa",
            "Zimbabwe": "Africa",
            "Africa (Region)": "Africa",
            "Asia and Pacific": "Asia",
            "Australia and New Zealand": "Oceania",
            "Caribbean": "North America",
            "Central America": "North America",
            "Central Asia and the Caucasus": "Asia",
            "East Asia": "Asia",
            "Eastern Europe": "Europe",
            "Europe": "Europe",
            "Middle East (Region)": "Middle East",
            "North Africa": "Africa",
            "North America": "North America",
            "Pacific Islands": "Oceania",
            "South America": "South America",
            "South Asia": "Asia",
            "Southeast Asia": "Asia",
            "Sub-Saharan Africa (Region)": "Africa",
            "Western Europe": "Europe",
            "Western Hemisphere (Region)": "North America",
            "ASEAN-5": "Asia",
            "Advanced economies": "World",
            "Emerging and Developing Asia": "World",
            "Emerging and Developing Europe": "World",
            "Emerging market and developing economies": "World",
            "Euro area": "Europe",
            "European Union": "Europe",
            "Latin America and the Caribbean": "North America",
            "Major advanced economies (G7)": "World",
            "Middle East and Central Asia": "Middle East",
            "Other advanced economies": "World",
            "Sub-Saharan Africa": "Africa",
            "World": "World"
        }

    def get_region(self, country):
        return self.country_region_dict.get(country, "Region not found")
