class CountryNameConverter:
    def __init__(self):
        self._country_names = {
            "ノルウェー": "Norway",
            "ドイツ": "Germany",
            "オーストリア": "Austria",
            "ポーランド": "Poland",
            "ハンガリー": "Hungary",
            "セルビア": "Serbia",
            "モンテネグロ": "Montenegro",
            "マケドニア": "North Macedonia",
            "アルバニア": "Albania",
            "スロベニア": "Slovenia",
            "クロアチア": "Croatia",
            "ボスニア・ヘルツェゴビナ": "Bosnia and Herzegovina",
            "ルーマニア": "Romania",
            "ブルガリア": "Bulgaria",
            "イタリア": "Italy",
            "マルタ": "Malta",
            "トルコ": "Turkey",
            "キプロス": "Cyprus",
            "ロシア": "Russia",
            "スウェーデン": "Sweden",
            "エストニア": "Estonia",
            "ラトビア": "Latvia",
            "リトアニア": "Lithuania",
            "ベラルーシ": "Belarus",
            "フィンランド": "Finland",
            "イギリス": "United Kingdom",
            "ウクライナ": "Ukraine",
            "モルドバ": "Moldova",
            "キルギス": "Kyrgyzstan",
            "ジョージア": "Georgia",
            "アゼルバイジャン": "Azerbaijan",
            "アルメニア": "Armenia",
            "トルクメニスタン": "Turkmenistan",
            "タジキスタン": "Tajikistan",
            "アイルランド": "Ireland",
            "シリア": "Syria",
            "レバノン": "Lebanon",
            "イスラエル": "Israel",
            "ヨルダン": "Jordan",
            "アイスランド": "Iceland",
            "サウジアラビア": "Saudi Arabia",
            "クウェート": "Kuwait",
            "イラク": "Iraq",
            "イラン": "Iran",
            "バーレーン": "Bahrain",
            "カタール": "Qatar",
            "アラブ首長国連邦": "United Arab Emirates",
            "オマーン": "Oman",
            "パキスタン": "Pakistan",
            "バングラデシュ": "Bangladesh",
            "インド": "India",
            "グリーンランド": "Greenland",
            "スリランカ": "Sri Lanka",
            "モルディブ": "Maldives",
            "モンゴル": "Mongolia",
            "ネパール": "Nepal",
            "中国（香港）": "Hong Kong SAR",
            "中国（マカオ）": "Macao SAR",
            "朝鮮民主主義人民共和国": "North Korea",
            "大韓民国": "South Korea",
            "日本": "Japan",
            "ミャンマー": "Myanmar",
            "タイ": "Thailand",
            "マレーシア": "Malaysia",
            "シンガポール": "Singapore",
            "ベトナム": "Vietnam",
            "ラオス": "Laos",
            "中華人民共和国": "China, People's Republic of",
            "スペイン（カナリア諸島）": "Spain (Canary Islands)",
            "モロッコ": "Morocco",
            "西サハラ": "Western Sahara",
            "デンマーク・フェロー諸島": "Faroe Islands",
            "スペイン（セウタ・メリリャ）": "Spain (Ceuta and Melilla)",
            "アルジェリア": "Algeria",
            "ニジェール": "Niger",
            "マリ": "Mali",
            "モーリタニア": "Mauritania",
            "セネガル": "Senegal",
            "ガンビア": "Gambia, The",
            "ギニア": "Guinea",
            "OCEAN ISLANDS": "Ocean Islands",
            "モーリシャス": "Mauritius",
            "リビア": "Libya",
            "エジプト": "Egypt",
            "オランダ": "Netherlands",
            "ソマリア": "Somalia",
            "エチオピア": "Ethiopia",
            "ウガンダ": "Uganda",
            "ケニア": "Kenya",
            "タンザニア": "Tanzania",
            "セイシェル": "Seychelles",
            "ベルギー": "Belgium",
            "コンゴ（民主共和国）": "Congo, Dem. Rep. of the",
            "ルワンダ": "Rwanda",
            "コンゴ（共和国）": "Congo, Republic of",
            "ガボン": "Gabon",
            "中央アフリカ": "Central African Republic",
            "チャド": "Chad",
            "赤道ギニア": "Equatorial Guinea",
            "カメルーン": "Cameroon",
            "ナイジェリア": "Nigeria",
            "ベナン": "Benin",
            "トーゴ": "Togo",
            "ガーナ": "Ghana",
            "ブルキナファソ": "Burkina Faso",
            "コートジボワール": "Côte d'Ivoire",
            "ルクセンブルク": "Luxembourg",
            "スイス・リヒテンシュタイン": "Switzerland",
            "アンゴラ": "Angola",
            "コモロ": "Comoros",
            "マダガスカル": "Madagascar",
            "モザンビーク": "Mozambique",
            "ザンビア": "Zambia",
            "マラウイ": "Malawi",
            "ナミビア": "Namibia",
            "ボツワナ": "Botswana",
            "南アフリカ": "South Africa",
            "スワジランド": "Eswatini",
            "フランス": "France",
            "アメリカ合衆国（アラスカ）": "United States (Alaska)",
            "カナダ": "Canada",
            "サンピエール・ミクロン": "Saint Pierre and Miquelon",
            "アメリカ合衆国": "United States",
            "メキシコ": "Mexico",
            "バミューダ諸島": "Bermuda",
            "バハマ": "Bahamas, The",
            "キューバ": "Cuba",
            "ケイマン諸島": "Cayman Islands",
            "ジャマイカ": "Jamaica",
            "ドミニカ共和国": "Dominican Republic",
            "プエルトリコ": "Puerto Rico",
            "ベリーズ": "Belize",
            "グアテマラ": "Guatemala",
            "エルサルバドル": "El Salvador",
            "ホンジュラス": "Honduras",
            "コスタリカ": "Costa Rica",
            "パナマ": "Panama",
            "アンギラ": "Anguilla",
            "セントクリストファー・ネイビス": "Saint Kitts and Nevis",
            "アンティグア・バーブーダ": "Antigua and Barbuda",
            "オランダ領アンティル・アルバ": "Netherlands Antilles (Aruba)",
            "オランダ領アンティル（キュラソー島とボネール島）": "Netherlands Antilles (Curaçao and Bonaire)",
            "グアドループ・サンマルタン・サンバルテレミ島": "Guadeloupe, Saint Martin, Saint Barthélemy",
            "ドミニカ国": "Dominica",
            "マルチニーク島": "Martinique",
            "セントルシア": "Saint Lucia",
            "セントビンセント": "Saint Vincent",
            "グレナダ": "Grenada",
            "トリニダード・トバゴ": "Trinidad and Tobago",
            "コロンビア": "Colombia",
            "スペイン": "Spain",
            "ギアナ": "Guyana",
            "スリナム": "Suriname",
            "フランス領ギアナ": "French Guiana",
            "ブラジル": "Brazil",
            "エクアドル": "Ecuador",
            "ペルー": "Peru",
            "ポルトガル": "Portugal",
            "ボリビア": "Bolivia",
            "チリ": "Chile",
            "カーボベルデ": "Cabo Verde",
            "パラグアイ": "Paraguay",
            "ウルグアイ": "Uruguay",
            "アルゼンチン": "Argentina",
            "STATIONS OPERATED BY ARGENTINA": "STATIONS OPERATED BY ARGENTINA",
            "STATIONS OPERATED BY THE RUSSIAN FEDERATION": "STATIONS OPERATED BY THE RUSSIAN FEDERATION",
            "STATIONS OPERATED BY CHILE": "STATIONS OPERATED BY CHILE",
            "STATIONS OPERATED BY CHINA": "STATIONS OPERATED BY CHINA",
            "STATIONS OPERATED BY THE U.S.A.": "STATIONS OPERATED BY THE U.S.A.",
            "STATIONS OPERATED BY SPAIN": "STATIONS OPERATED BY SPAIN",
            "STATIONS OPERATED BY NORWAY": "STATIONS OPERATED BY NORWAY",
            "STATIONS OPERATED BY INDIA": "STATIONS OPERATED BY INDIA",
            "STATIONS OPERATED BY AUSTRALIA": "STATIONS OPERATED BY AUSTRALIA",
            "ISLANDS（北半球太平洋域）": "ISLANDS (North Pacific)",
            "ソロモン諸島": "Solomon Islands",
            "バヌアツ": "Vanuatu",
            "ニューカレドニア": "New Caledonia",
            "キリバス": "Kiribati",
            "ツバル": "Tuvalu",
            "フィジー共和国": "Fiji",
            "トケラウ諸島": "Tokelau",
            "DETACHED ISLANDS": "DETACHED ISLANDS",
            "サモア・米領サモア": "Samoa (American Samoa)",
            "トンガ": "Tonga",
            "クック諸島": "Cook Islands",
            "ニウエ": "Niue",
            "フランス領ポリネシア（マルキーズ諸島）": "French Polynesia (Marquesas Islands)",
            "フランス領ポリネシア（ソシエテ諸島）": "French Polynesia (Society Islands)",
            "フランス領ポリネシア（トゥアモトゥ諸島・ガンビエル諸島）": "French Polynesia (Tuamotu and Gambier Islands)",
            "フランス領ポリネシア（AUSTRAL ISLANDS）": "French Polynesia (Austral Islands)",
            "ニュージーランド": "New Zealand",
            "オーストラリア": "Australia",
            "インドネシア": "Indonesia",
            "ブルネイ": "Brunei Darussalam",
            "ISLANDS": "ISLANDS",
            "フィリピン": "Philippines",
            "カンボジア": "Cambodia"

        }

    def get_english_name(self, japanese_name):
        """
        Get the English name of a country or region given its Japanese name.

        Args:
            japanese_name (str): The Japanese name of the country or region.

        Returns:
            str: The corresponding English name, or None if not found.
        """
        return self._country_names.get(japanese_name)

    def get_english_name_list(self):
        return list(self._country_names.values())
